
[nfs]
172.31.28.150 ansible_ssh_user='ec2-user'

[webservers]
172.31.85.53 ansible_ssh_user='ec2-user'
172.31.93.175 ansible_ssh_user='ec2-user'

[db]
172.31.93.234 ansible_ssh_user='ubuntu' 

[lb]
172.31.81.167 ansible_ssh_user='ubuntu'

